### ISSUE TITLE
fix to work on php 7.2

### ISSUE THREAD

**Issue by albertborsos** [LucidTaZ/yii2-scssphp#10]
I would like to test your plugin but it is not working on php 7.2.
The `"leafo/scssphp": "^0.6.3"` dependency is out of date. Please update it to `^0.7.5`. Thanks.

**Comment by LucidTaZ** [comment]
Hi, thanks for the report. I'll look into this as soon as I have time.

Last time I checked, Yii wasn't ready for PHP 7.2 yet. I didn't use it in a while, but that was so far the reason why I didn't support it here either.

**Comment by LucidTaZ** [comment]
Thank you kindly for the PR. I've just tagged 0.2.0 for the higher dependency constraint.

**Comment by albertborsos** [comment]
You're welcome :)
