### ISSUE TITLE
[idea] check the modification time of every scss files in the source path of the assetbundle

### ISSUE THREAD

**Issue by albertborsos** [LucidTaZ/yii2-scssphp#14]
not just of the the main scss file.

**Comment by LucidTaZ** [comment]
Thanks for the suggestion. I thought about it but it's not really easy to do for the following reasons:

To accurately know if an SCSS file or any of its dependencies were updated, the SCSS file would have to be parsed to know which dependencies it has. This is already a performance impact so it would be much simpler to set the `$forceConvert` attribute to true instead.

We could also check the entire directory tree of the SCSS file for any (possibly unrelated) SCSS files and if anything is newer, then recompile every target file that is older. But a dependency is not guaranteed to be a descendant of the SCSS file in the directory, so it would require more complexity as well.

So to keep things simple I think it's better to keep the current behaviour. I understand it can be annoying or unintuitive, but it's the same as the default Yii behaviour. (`vendor/yiisoft/yii2/web/AssetConverter.php`)
