### ISSUE TITLE
Package leafo/scssphp is abandoned

### ISSUE THREAD

**Issue by vladovinkin** [LucidTaZ/yii2-scssphp#20]
Your package has dependency:
leafo/scssphp.

Composer return warning:
Package leafo/scssphp is abandoned, you should avoid using it. Use scssphp/scssphp instead.

**Comment by LucidTaZ** [comment]
Thanks, I've changed to the newer library and tagged the upgrade in lucidtaz/yii2-scssphp version 0.3.0.
