### ISSUE TITLE
Can you change the dependency on guzzlehttp/guzzle to a version 7.x?

### ISSUE THREAD

**Issue by gb5256** [LucidTaZ/yii2-scssphp#22]
I am trying to use your latest 0.3.0 but get composer update errors all over the place, pointing to the guzzle version 6.x you have in the composer.json.

Is this a hard requirement to use version 6.x? or can you switch to 7.x easily?

Thanks for your thoughts on this one,
gb5256

**Comment by LucidTaZ** [comment]
Hi, thanks for your issue. I'm not actively maintaining this project anymore, but I'm definitely open to pull requests with version upgrades. There is no hard requirement; the simple reason is that 6.x was the latest version back when this project was still maintained.

**Comment by LucidTaZ** [comment]
Fixed by: #24
